# Generated by Django 3.2.12 on 2022-03-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=21)),
                ('sex', models.CharField(default=0, max_length=1)),
                ('address', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
