# Generated by Django 3.2.12 on 2022-03-08 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stu',
            name='address',
        ),
    ]
