# Generated by Django 3.2.12 on 2022-03-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0002_remove_stu_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu',
            name='size',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
