# Generated by Django 3.2.12 on 2022-03-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0004_auto_20220308_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu',
            name='password',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
