# Generated by Django 3.2.12 on 2022-03-13 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuperNum',
        ),
    ]
