# Generated by Django 3.2.12 on 2022-03-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_supernum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='工资'),
        ),
    ]
